### ISSUE TITLE
ALICE bot outputing Alexa stuff

### ISSUE THREAD

**Issue by NicolasAG** [NicolasAG/convai#7]
When chatting with the bot and asking "What is your name?" the answer returned by ALICEBOT is "My name is Alexa Prize Social Bot". We need to avoid that so that users never select this candidate response in data collection phases!

**Comment by NicolasAG** [comment]
oh ok good to know, will have to check that first then

**Comment by koustuvsinha** [comment]
Relevant lines: https://github.com/NicolasAG/convai/blob/master/models/wrapper.py#L804-L813
